services:
  # Banco de Dados PostgreSQL
  db:
    image: postgres:16-alpine
    container_name: capicash_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: capicash_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # Interface visual para gerenciar o banco
  pgadmin:
    image: dpage/pgadmin4
    container_name: capicash_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@capicash.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
